export const KnowledgeBaseCopy = {
    title: `Get All The Answers To Your Concerns Here.`,
    img: `/images/ducehost-knowlegebase-help-system.webp`,
    width: `418`,
    height: `418`,
}

export const KnowledgeBaseCategories = [
    {
        id: `dns01`,
        title: `Domain Name Search`,
        slug: `category-domain-name-search`,
        articles: [
            {
                id: `dns110001`,
                topic: `How to purchase a domain name`,
                link: `how-to-purchase-a-domain-name`,
                body: `<p>If you are searching for the ideal domain name for your project, go to the Domain Checker, enter your desired domain name and click on Search Domain. You will be able to buy the domain right away, if it is available, by adding it to the cart:<br/>
                You will also be presented with more options of domain endings (also known as extensions or TLD) that you can register as well in order to boost your brand:<br/>
                Select all the domains you want to purchase and continue to the cart, where you will find the renewal price and have the option to select the renewal period.</p>
                <h3>What to Do if the Domain Name Is Not Available</h3>
                <p>If you are searching for the ideal domain name for your project, go to the Domain Checker, enter your desired domain name and click on Search Domain. You will be able to buy the domain right away, if it is available, by adding it to the cart:<br/>
                You will also be presented with more options of domain endings (also known as extensions or TLD) that you can register as well in order to boost your brand:<br/>
                Select all the domains you want to purchase and continue to the cart, where you will find the renewal price and have the option to select the renewal period.</p>`,
                category: `Domain Name Search`,
                categorySlug: `category-domain-name-search`,
                likes: `32`,
                dislikes: `7`,
                lastUpdated: "Nov, 2023",
            },
            {
                id: `dns110002`,
                topic: `How to register a domain name`,
                link: `how-to-register-a-domain-name`,
                body: `<p>To register a domain name, follow these steps:</p>
                <ol>
                <li>Choose a Domain Registrar: Select a reputable domain registrar, like GoDaddy, Namecheap, or Google Domains.</li>
                <li>Search for Domain Availability: Use the registrar's search tool to check if your desired domain name is available.</li>
                <li>Select Domain and Extension: Once you find an available domain, choose the domain name and the extension (e.g., .com, .net, .org).</li>
                <li>Add to Cart: Add the selected domain to your shopping cart and review your order.</li>
                <li>Provide Contact Information: During checkout, you'll need to provide accurate contact information as it's a requirement for domain registration.</li>
                <li>Choose Registration Period: Select the duration for which you want to register the domain (usually in yearly increments).</li>
                <li>Privacy Protection (Optional): Consider opting for WHOIS privacy protection to keep your contact details private.</li>
                <li>Complete Payment: Pay for the domain registration through the provided payment methods.</li>
                <li>Confirm Purchase: Review your order one more time and confirm the purchase.</li>
                <li>Access Domain Control Panel: Once registered, you can access your domain control panel to manage settings like DNS and domain forwarding.</li>
                </ol>
                <p>In summary, to register a domain name, choose a registrar, search for availability, select a domain and extension, provide contact information, choose the registration period, consider privacy protection, complete payment, confirm the purchase, and access your domain control panel for management.</p>`,
                category: `Domain Name Search`,
                categorySlug: `category-domain-name-search`,
                likes: `32`,
                dislikes: `7`,
                lastUpdated: "Feb, 2023",
            },
            {
                id: `dns110003`,
                topic: `How to change DNS for a domain`,
                link: `how-to-change-dns-for-a-domain `,
                body: `lorem`,
                category: `Domain Name Search`,
                categorySlug: `category-domain-name-search`,
                likes: `32`,
                dislikes: `7`,
                lastUpdated: "Jan, 2023",
            },
            {
                id: `dns110004`,
                topic: `What is Domain Name Server (DNS)?`,
                link: `what-is-domain-name-server`,
                body: `<p>A DNS server, or Domain Name System server, is a crucial component of the internet infrastructure. It acts as a translator between human-readable domain names (e.g., example.com) and their corresponding IP addresses (e.g., 192.168.0.1). DNS servers are responsible for converting domain names into IP addresses and vice versa, allowing users to access websites and services using memorable domain names.</p>`,
                category: `Domain Name Search`,
                categorySlug: `category-domain-name-search`,
                likes: `32`,
                dislikes: `7`,
                lastUpdated: "Dec, 2023",
            },
            {
                id: `dns110005`,
                topic: `DNS propagation explained`,
                link: `how-to-register-a-domain-name`,
                body: `lorem`,
                category: `Domain Name Search`,
                categorySlug: `category-domain-name-search`,
                likes: `32`,
                dislikes: `7`,
                lastUpdated: `May, 2023`,
            },
            {
                id: `dns110006`,
                topic: `What to do with an unwanted domain?`,
                link: `What-to-do-with-an-unwanted-domain`,
                body: `lorem`,
                category: `Domain Name Search`,
                categorySlug: `category-domain-name-search`,
                likes: `32`,
                dislikes: `7`,
                lastUpdated: `May, 2023`,
            },
        ]
    },
    {
        id: `dt02`,
        title: `Domain Transfer`,
        slug: `category-domain-transfer`,
        articles: [
            {
                id: `dt210001`,
                topic: `How to purchase a domain name`,
                link: `how-to-purchase-a-domain-name`,
                body: `lorem How to purchase a domain name Copy`,
                category: `Domain Transfer`,
                categorySlug: `category-domain-transfer`,
                likes: `54`,
                dislikes: `2`,
                lastUpdated: `Aug, 2023`,
            },
            {
                id: `dt210002`,
                topic: `How to register a domain name`,
                link: `how-to-register-a-domain-name`,
                body: `lorem`,
                category: `Domain Transfer`,
                categorySlug: `category-domain-transfer`,
                likes: `27`,
                dislikes: `2`,
                lastUpdated: `Nov, 2023`,
            },
            {
                id: `dt210003`,
                topic: `How to change DNS for a domain`,
                link: `how-to-change-dns-for-a-domain `,
                body: `lorem`,
                category: `Domain Transfer`,
                categorySlug: `category-domain-transfer`,
                likes: `18`,
                dislikes: `2`,
                lastUpdated: `Oct, 2023`,
            },
            {
                id: `dt210004`,
                topic: `What is Domain Name Server (DNS)?`,
                link: `what-is-domain-name-server`,
                body: `lorem`,
                category: `Domain Transfer`,
                categorySlug: `category-domain-transfer`,
                likes: `45`,
                dislikes: `0`,
                lastUpdated: `Jan, 2024`,
            },
            {
                id: `dt210005`,
                topic: `DNS propagation explained`,
                link: `dns-propagation-explained`,
                body: `lorem`,
                category: `Domain Transfer`,
                categorySlug: `category-domain-transfer`,
                likes: `81`,
                dislikes: `1`,
                lastUpdated: `May, 2022`,
            },
            {
                id: `dt210006`,
                topic: `What to do with an unwanted domain?`,
                link: `What-to-do-with-an-unwanted-domain`,
                body: `lorem`,
                category: `Domain Transfer`,
                categorySlug: `category-domain-transfer`,
                likes: `63`,
                dislikes: `0`,
                lastUpdated: `Dec, 2023`,
            },
            {
                id: `dt210007`,
                topic: `What is domain transfer?`,
                link: `what-is-domain-transfer`,
                body: `lorem`,
                category: `Domain Transfer`,
                categorySlug: `category-domain-transfer`,
                likes: `73`,
                dislikes: `0`,
                lastUpdated: `Jun, 2023`,
            },
            {
                id: `dt210008`,
                topic: `How to transfer a domain`,
                link: `how-to-transfer-a-domain`,
                body: `lorem`,
                category: `Domain Transfer`,
                categorySlug: `category-domain-transfer`,
                likes: `29`,
                dislikes: `0`,
                lastUpdated: `Jan, 2024`,
            },
        ]
    },
    {
        id: `wl03`,
        title: `Whois Lookup`,
        slug: `category-whois-lookup`,
        articles: [
            {
                id: `wl310001`,
                topic: `How to purchase a domain name`,
                link: `how-to-purchase-a-domain-name`,
                body: `lorem How to purchase a domain name Copy`,
                category: `Whois Lookup`,
                categorySlug: `category-whois-lookup`,
                likes: `77`,
                dislikes: `2`,
                lastUpdated: "May, 2023",
            },
            {
                id: `wl310002`,
                topic: `How to register a domain name`,
                link: `how-to-register-a-domain-name`,
                body: `lorem`,
                category: `Whois Lookup`,
                categorySlug: `category-whois-lookup`,
                likes: `52`,
                dislikes: `2`,
                lastUpdated: "Jan, 2024",
            },
            {
                id: `wl310003`,
                topic: `How to change DNS for a domain`,
                link: `how-to-change-dns-for-a-domain `,
                body: `lorem`,
                category: `Whois Lookup`,
                categorySlug: `category-whois-lookup`,
                likes: `53`,
                dislikes: `2`,
                lastUpdated: "Jan, 2024",
            },
            {
                id: `wl310004`,
                topic: `What is Domain Name Server (DNS)?`,
                link: `how-to-purchase-a-domain-name`,
                body: `lorem`,
                category: `Whois Lookup`,
                categorySlug: `category-whois-lookup`,
                likes: `61`,
                dislikes: `0`,
                lastUpdated: "Nov, 2023",
            },
            {
                id: `wl310005`,
                topic: `DNS propagation explained`,
                link: `how-to-register-a-domain-name`,
                body: `lorem`,
                category: `Whois Lookup`,
                categorySlug: `category-whois-lookup`,
                likes: `87`,
                dislikes: `1`,
                lastUpdated: "Feb, 2024",
            },
            {
                id: `wl310006`,
                topic: `What to do with an unwanted domain?`,
                link: `What-to-do-with-an-unwanted-domain`,
                body: `lorem`,
                category: `Whois Lookup`,
                categorySlug: `category-whois-lookup`,
                likes: `58`,
                dislikes: `0`,
                lastUpdated: "Feb, 2024",
            },
            {
                id: `wl310007`,
                topic: `What is Whois?`,
                link: `what-is-whois`,
                body: `What is Whois - lorem`,
                category: `Whois Lookup`,
                categorySlug: `category-whois-lookup`,
                likes: `58`,
                dislikes: `0`,
                lastUpdated: "Jan, 2024",
            },
        ]
    },
    {
        id: `sh04`,
        title: `Shared Hosting`,
        slug: `category-shared-hosting`,
        articles: [
            {
                id: `sh410001`,
                topic: `How to purchase a domain name`,
                link: `how-to-purchase-a-domain-name`,
                body: `lorem How to purchase a domain name Copy`,
                category: `Shared Hosting`,
                categorySlug: `category-shared-hosting`,
                likes: `32`,
                dislikes: `2`,
                lastUpdated: "Feb, 2024",
            },
            {
                id: `sh410002`,
                topic: `How to register a domain name`,
                link: `how-to-register-a-domain-name`,
                body: `lorem`,
                category: `Shared Hosting`,
                categorySlug: `category-shared-hosting`,
                likes: `32`,
                dislikes: `2`,
                lastUpdated: "Oct, 2023",
            },
            {
                id: `sh410003`,
                topic: `How to change DNS for a domain`,
                link: `how-to-change-dns-for-a-domain `,
                body: `lorem`,
                category: `Shared Hosting`,
                categorySlug: `category-shared-hosting`,
                likes: `32`,
                dislikes: `2`,
                lastUpdated: "Jan, 2024",
            },
            {
                id: `sh410004`,
                topic: `What is Domain Name Server (DNS)?`,
                link: `how-to-purchase-a-domain-name`,
                body: `lorem`,
                category: `Shared Hosting`,
                categorySlug: `category-shared-hosting`,
                likes: `32`,
                dislikes: `0`,
                lastUpdated: "Jan, 2023",
            },
            {
                id: `sh410005`,
                topic: `DNS propagation explained`,
                link: `how-to-register-a-domain-name`,
                body: `lorem`,
                category: `Shared Hosting`,
                categorySlug: `category-shared-hosting`,
                likes: `32`,
                dislikes: `1`,
                lastUpdated: "Jun, 2023",
            },
            {
                id: `sh410006`,
                topic: `What to do with an unwanted domain?`,
                link: `What-to-do-with-an-unwanted-domain`,
                body: `lorem`,
                category: `Shared Hosting`,
                categorySlug: `category-shared-hosting`,
                likes: `32`,
                dislikes: `0`,
                lastUpdated: "Jun, 2023",
            },
            {
                id: `sh410007`,
                topic: `What is Shared Hosting?`,
                link: `what-is-shared-hosting`,
                body: `lorem`,
                category: `Shared Hosting`,
                categorySlug: `category-shared-hosting`,
                likes: `19`,
                dislikes: `0`,
                lastUpdated: "May, 2023",
            },
        ]
    },
    {
        id: `rh05`,
        title: `Reseller Hosting`,
        slug: `category-reseller-hosting`,
        articles: [
            {
                id: `rh510001`,
                topic: `How to purchase a domain name`,
                link: `how-to-purchase-a-domain-name`,
                body: `lorem How to purchase a domain name Copy`,
                category: `Reseller Hosting`,
                categorySlug: `category-reseller-hosting`,
                likes: `4`,
                dislikes: `0`,
                lastUpdated: "Jan, 2024",
            },
            {
                id: `rh510002`,
                topic: `How to register a domain name`,
                link: `how-to-register-a-domain-name`,
                body: `lorem`,
                category: `Reseller Hosting`,
                categorySlug: `category-reseller-hosting`,
                likes: `17`,
                dislikes: `0`,
                lastUpdated: "Jan, 2024",
            },
            {
                id: `rh510003`,
                topic: `How to change DNS for a domain`,
                link: `how-to-change-dns-for-a-domain `,
                body: `lorem`,
                category: `Reseller Hosting`,
                categorySlug: `category-reseller-hosting`,
                likes: `12`,
                dislikes: `2`,
                lastUpdated: "Jan, 2024",
            },
            {
                id: `rh510004`,
                topic: `What is Domain Name Server (DNS)?`,
                link: `how-to-purchase-a-domain-name`,
                body: `lorem`,
                category: `Reseller Hosting`,
                categorySlug: `category-reseller-hosting`,
                likes: `32`,
                dislikes: `0`,
                lastUpdated: "Jan, 2024",
            },
            {
                id: `rh510005`,
                topic: `DNS propagation explained`,
                link: `how-to-register-a-domain-name`,
                body: `lorem`,
                category: `Reseller Hosting`,
                categorySlug: `category-reseller-hosting`,
                likes: `32`,
                dislikes: `1`,
                lastUpdated: "Jan, 2024",
            },
            {
                id: `510006`,
                topic: `What to do with an unwanted domain?`,
                link: `what-to-do-with-an-unwanted-domain`,
                body: `lorem`,
                category: `Reseller Hosting`,
                categorySlug: `category-reseller-hosting`,
                likes: `78`,
                dislikes: `0`,
                lastUpdated: "Feb, 2024",
            },
            {
                id: `rh510007`,
                topic: `What are the Benefits of Reseller Hosting?`,
                link: `what-are-the-benefits-of-reseller-hosting`,
                body: `lorem`,
                category: `Reseller Hosting`,
                categorySlug: `category-reseller-hosting`,
                likes: `13`,
                dislikes: `0`,
                lastUpdated: "Jan, 2024",
            },
            {
                id: `rh510008`,
                topic: `What is Reseller Hosting?`,
                link: `what-is-reseller-hosting`,
                body: `lorem`,
                category: `Reseller Hosting`,
                categorySlug: `category-reseller-hosting`,
                likes: `78`,
                dislikes: `0`,
                lastUpdated: "Feb, 2024",
            },
        ]
    },
    {
        id: `wh06`,
        title: `WordPress Hosting`,
        slug: `category-wordPress-hosting`,
        articles: [
            {
                id: `wh610001`,
                topic: `How to purchase a domain name`,
                link: `how-to-purchase-a-domain-name`,
                body: `lorem How to purchase a domain name Copy`,
                category: `WordPress Hosting`,
                categorySlug: `category-wordPress-hosting`,
                likes: `252`,
                dislikes: `2`,
                lastUpdated: "Sep, 2023",
            },
            {
                id: `wh610002`,
                topic: `How to register a domain name`,
                link: `how-to-register-a-domain-name`,
                body: `lorem`,
                category: `WordPress Hosting`,
                categorySlug: `category-wordPress-hosting`,
                likes: `51`,
                dislikes: `2`,
                lastUpdated: "Sep, 2023",
            },
            {
                id: `wh610003`,
                topic: `How to change DNS for a domain`,
                link: `how-to-change-dns-for-a-domain `,
                body: `lorem`,
                category: `WordPress Hosting`,
                categorySlug: `category-wordPress-hosting`,
                likes: `22`,
                dislikes: `2`,
                lastUpdated: "Sep, 2023",
            },
            {
                id: `wh610004`,
                topic: `What is Domain Name Server (DNS)?`,
                link: `how-to-purchase-a-domain-name`,
                body: `lorem`,
                category: `WordPress Hosting`,
                categorySlug: `category-wordPress-hosting`,
                likes: `51`,
                dislikes: `0`,
                lastUpdated: "Sep, 2023",
            },
            {
                id: `wh610005`,
                topic: `DNS propagation explained`,
                link: `how-to-register-a-domain-name`,
                body: `lorem`,
                category: `WordPress Hosting`,
                categorySlug: `category-wordPress-hosting`,
                likes: `14`,
                dislikes: `1`,
                lastUpdated: "Sep, 2023",
            },
            {
                id: `wh610006`,
                topic: `What to do with an unwanted domain?`,
                link: `What-to-do-with-an-unwanted-domain`,
                body: `lorem`,
                category: `WordPress Hosting`,
                categorySlug: `category-wordPress-hosting`,
                likes: `37`,
                dislikes: `0`,
                lastUpdated: "Sep, 2023",
            },
        ]
    },
]

export const KnowledgeBaseMostRead = [
    {
        title: `How to purchase a domain name`,
        link: `/help/knowledge-base/category-domain-name-search/how-to-purchase-a-domain-name`,
        category: `Domain Name Search`
    },
    {
        title: `What is domain transfer`,
        link: `/help/knowledge-base/category-domain-transfer/what-is-domain-transfer`,
        category: `Domain Transfer`
    },
    {
        title: `What is Whois?`,
        link: `/help/knowledge-base/category-whois-lookup/what-is-whois`,
        category: `Whois Lookup`
    },
    {
        title: `What is Shared hosting?`,
        link: `/help/knowledge-base/category-shared-hostingy/what-is-shared-hosting`,
        category: `Shared Hosting`
    },
    {
        title: `What is Reseller Hosting`,
        link: `/help/knowledge-base/category-reseller-hosting/what-is-reseller-hosting`,
        category: `Reseller Hosting`
    },
    {
        title: `What are the Benefits of Reseller Hosting?`,
        link: `/help/knowledge-base/category-reseller-hosting/what-are-the-benefits-of-reseller-hosting`,
        category: `Reseller Hosting`
    },
    {
        title: `How to register a domain name`,
        link: `/help/knowledge-base/category-domain-name-search/how-to-register-a-domain-name`,
        category: `Domain Name Search`
    },
    {
        title: `How to transfer a domain`,
        link: `/help/knowledge-base/category-domain-transfer/how-to-transfer-a-domain`,
        category: `Domain Transfer`
    },
]