export const PrivacyPolicyCopy = {
    Date: `Effective Date: 2022-08-17`,
    Policies: [
        {
            Title: `Introduction`,
            Body: `<p>Welcome to Ducehost.</p>
            <p>Ducehost (“us”, “we”, or “our”) operates <a href='https://ducehost.com' target="_blank" rel="noopener noreferrer">https://ducehost.com</a> (hereinafter referred to as “Service”).</p>
            <p>Our Privacy Policy governs your visit to <a href='https://ducehost.com' target="_blank" rel="noopener noreferrer">https://ducehost.com</a>, and explains how we collect, safeguard and disclose information that results from your use of our Service.</p>
            <p>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
            <p>Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).</p>`,
        },
        {
            Title: `Definitions`,
            Body: `<p><span class='wine'>SERVICE</span> means the <a href='https://ducehost.com' target="_blank" rel="noopener noreferrer">https://ducehost.com</a> website operated by Ducehost.</p>
            <p><span class='wine'>PERSONAL DATA</span> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
            <p><span class='wine'>USAGE DATA</span> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
            <p><span class='wine'>COOKIES</span> are small files stored on your device (computer or mobile device).</p>
            <p><span class='wine'>DATA CONTROLLER</span> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
            <p><span class='wine'>DATA PROCESSORS (OR SERVICE PROVIDERS)</span> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
            <p><span class='wine'>DATA SUBJECT</span> is any living individual who is the subject of Personal Data.</p>
            <p><span class='wine'>THE USER</span> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>`,
        },
        {
            Title: `Information Collection and Use`,
            Body: `<p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>`,
        },
        {
            Title: `Types of Data Collected`,
            Body: `<p><span class='wine'>Personal Data</span></p>
            <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:</p>
            <ol>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, Country, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
            </ol>
            <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p>
            
            <p><span class='wine'>Usage Data</span></p>
            <p>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”).</p>
            <p>This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.</p>
            
            <p><span class='wine'>Location Data</span></p>
            <p>We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.</p>
            <p>You can enable or disable location services when you use our Service at any time by way of your device settings.</p>
            
            <p><span class='wine'>Tracking Cookies Data</span></p>
            <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
            <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.</p>
            <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
            <p>Examples of Cookies we use:</p>
            <ol>
            <li> Session Cookies: We use Session Cookies to operate our Service.</li>
            <li> Preference Cookies: We use Preference Cookies to remember your preferences and various settings.</li>
            <li> Security Cookies: We use Security Cookies for security purposes.</li>
            <li> Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
            </ol>
            
            <p><span class='wine'>Other Data</span></p>
            <p>While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.</p>`,
        },
        {
            Title: `Use of Data`,
            Body: `<p>Ducehost uses the collected data for various purposes:</p>
            <ol>
            <li>0.1. to provide and maintain our Service;</li>
            <li>0.2. to notify you about changes to our Service;</li>
            <li>0.3. to allow you to participate in interactive features of our Service when you choose to do so;</li>
            <li>0.4. to provide customer support;</li>
            <li>0.5. to gather analysis or valuable information so that we can improve our Service;</li>
            <li>0.6. to monitor the usage of our Service;</li>
            <li>0.7. to detect, prevent and address technical issues;</li>
            <li>0.8. to fulfil any other purpose for which you provide it;</li>
            <li>0.9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
            <li>0.10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
            <li>0.11. to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
            <li>0.12. in any other way we may describe when you provide the information;</li>
            <li>0.13. for any other purpose with your consent.</li>
            <ol>`,
        },
        {
            Title: `Retention of Data`,
            Body: `<p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
            We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>`,
        },
        {
            Title: `Transfer of Data`,
            Body: `<p>Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
            <p>If you are located outside UK and choose to provide information to us, please note that we transfer the data, including Personal Data, to UK and process it there.
            Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
            <p>Ducehost will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>`,
        },
        {
            Title: `Disclosure of Data`,
            Body: `<p>We may disclose personal information that we collect, or you provide:</p>
            <ol>
            <li>0.1. Disclosure for Law Enforcement.</li>
            <p>Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
            <li>0.2. Business Transaction.</li>
            <p>If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</p>
            <li>0.3. Other cases. We may disclose your information also:</li>
            <ol>
            <li>0.3.1. to our subsidiaries and affiliates;</li>
            <li>0.3.2. to contractors, service providers, and other third parties we use to support our business;</li>
            <li>0.3.3. to fulfill the purpose for which you provide it;</li>
            <li>0.3.4. for the purpose of including your company’s logo on our website;</li>
            <li>0.3.5. for any other purpose disclosed by us when you provide the information;</li>
            <li>0.3.6. with your consent in any other cases;</li>
            <li>0.3.7. if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</li>
            </ol>
            </ol>`,
        },
        {
            Title: `Security of Data`,
            Body: `<p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>`,
        },
        {
            Title: `Your Data Protection Rights Under General Data Protection Regulation (GDPR)`,
            Body: `<p>If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.</p>
            <p>We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
            <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at ducehost@gmail.com.</p>
            <p>In certain circumstances, you have the following data protection rights:</p>
            <ol>
            <li>0.1. the right to access, update or to delete the information we have on you;</li>
            <li>0.2. the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
            <li>0.3. the right to object. You have the right to object to our processing of your Personal Data;</li>
            <li>0.4. the right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
            <li>0.5. the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
            <li>0.6. the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</li>
            </ol>
            <p>Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.</p>
            <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>`,
        },
        {
            Title: `Service Providers`,
            Body: `<p>We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
            <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>`,
        },
        {
            Title: `Analytics`,
            Body: `<p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>`,
        },
        {
            Title: `CI/CD tools`,
            Body: `<p>We may use third-party Service Providers to automate the development process of our Service.</p>`,
        },
        {
            Title: `Behavioral Remarketing`,
            Body: `<p>We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</p>`,
        },
        {
            Title: `Payments`,
            Body: `<p>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).
            We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>`,
        },
        {
            Title: `Links to Other Sites`,
            Body: `<p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>`,
        },
        {
            Title: `Children’s Privacy`,
            Body: `<p>Our Services are not intended for use by children under the age of 18 (“Child” or “Children”).</p>
            <p>We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</p>`,
        },
        {
            Title: `Changes to This Privacy Policy`,
            Body: `<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
            <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.</p>
            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>`,
        },
        {
            Title: `Contact Us`,
            Body: `<p>If you have any questions about this Privacy Policy, please contact us by email: <a href='mailto:ducehost@gmail.com'>ducehost@gmail.com</a>.</p>`,
        },
    ]
}